# Generated by Django 3.2.12 on 2023-12-14 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231214_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
